// Das Kochbuch: sehr einfache Rezepte für 2, aufgebaut auf dem, was Julia mag (fav: true = von ihrer Liste).
// plate: was der Teller schon hat — kh (Sättigungsbeilage), ew (Eiweiß), gm (Gemüse). Fehlt etwas, schlägt die App
// passende SIDES vor (ein Tipp, und sie kommen mit auf die Einkaufsliste und in den Kochmodus).
// ing: [Menge, Zutat] · steps: [Text, Minuten für den Timer (optional)] · Abkürzungen sind ausdrücklich erlaubt.

export const CATS = [['haupt', '🍽️ Hauptgerichte'], ['salat', '🥗 Salate'], ['dessert', '🍨 Desserts'], ['drink', '🍹 Drinks ohne Alkohol']];
export const PLATE = { kh: ['🍝', 'Sättigung'], ew: ['🥩', 'Eiweiß'], gm: ['🥦', 'Gemüse'] };

export const RECIPES = [
  // ---------- ihre Lieblinge ----------
  { id: 'koettbullar', fav: true, cat: 'haupt', title: 'Köttbullar mit Kartoffelpüree & Erbsen', icon: '🧆', min: 25, tags: ['schwedisch', 'deftig', 'schnell'], plate: { kh: 1, ew: 1, gm: 1 },
    ing: [['1 Packung (ca. 500 g)', 'Köttbullar (TK)'], ['1 Beutel', 'Kartoffelpüree (Pulver)'], ['400 ml', 'Milch'], ['300 g', 'Erbsen (TK)'], ['200 ml', 'Sahne'], ['1', 'Brühwürfel'], ['1 TL', 'Senf'], ['1 Glas', 'Preiselbeeren']],
    steps: [['Köttbullar in einer Pfanne mit etwas Öl rundum braun braten.', 10], ['Sahne, 100 ml Wasser, Brühwürfel und Senf dazu, kurz köcheln – fertig ist die Soße.', 5],
            ['Püree nach Packung mit der Milch anrühren.'], ['Erbsen in einem Topf mit etwas Wasser und einem Stück Butter warm machen.', 5], ['Alles auf den Teller, Preiselbeeren dazu. Hej hej!']] },
  { id: 'kohlpfanne', fav: true, cat: 'haupt', title: 'Kohlrouladen-Pfanne mit brauner Soße', icon: '🥬', min: 35, tags: ['deftig', 'hausmannskost'], plate: { kh: 1, ew: 1, gm: 1 },
    note: 'Schmeckt wie Kohlrouladen – nur ohne Wickeln.',
    ing: [['400 g', 'Hackfleisch (gemischt)'], ['½ Kopf (ca. 600 g)', 'Spitzkohl oder Weißkohl'], ['1', 'Zwiebel'], ['1 Päckchen', 'Bratensoße (Pulver)'], ['600 g', 'Kartoffeln (festkochend)'], ['1 TL', 'Kümmel (wer mag)']],
    steps: [['Kartoffeln schälen, halbieren und in Salzwasser kochen.', 20], ['Kohl in Streifen schneiden, Zwiebel würfeln.'], ['Hack in einer großen Pfanne krümelig braten, Zwiebel dazu.', 5],
            ['Kohl dazu, salzen, pfeffern, Kümmel – 10 Minuten mitbraten, bis er weich ist.', 10], ['Bratensoße nach Packung anrühren, drübergießen, kurz aufkochen. Mit den Kartoffeln servieren.']] },
  { id: 'schweinsbraten', fav: true, cat: 'haupt', title: 'Schweinsbraten mit Knödel & Sauerkraut', icon: '🍖', min: 130, tags: ['deftig', 'österreichisch', 'ofen', 'sonntag'], plate: { kh: 1, ew: 1, gm: 1 },
    note: 'Klingt nach viel – ist aber fast nur Warten. Der Ofen macht die Arbeit.',
    ing: [['ca. 1 kg', 'Schweinebraten mit Schwarte (Schulter oder Bauch, beim Metzger rautenförmig einschneiden lassen)'], ['1', 'Zwiebel'], ['1 TL', 'Kümmel'], ['330 ml', 'Bier oder Brühe'], ['1 Packung', 'Kartoffelknödel im Kochbeutel'], ['1 Dose', 'Sauerkraut']],
    steps: [['Ofen auf 180 °C (Umluft 160 °C). Fleisch rundum mit Salz und Kümmel einreiben, besonders gut in die Schwarte.'], ['Zwiebel vierteln, mit dem Fleisch (Schwarte nach oben) in einen Bräter, Bier drunter gießen.'],
            ['Ab in den Ofen. Zwischendurch etwas Wasser nachgießen, wenn es trocken wird.', 110], ['Für die Kruste: die letzten 15 Minuten den Grill an – dabei bleiben, die Schwarte poppt auf!', 15],
            ['Währenddessen Knödel nach Packung kochen und Sauerkraut im Topf warm machen.', 20], ['Fleisch aufschneiden, den Saft aus dem Bräter als Soße drüber.']] },
  { id: 'lachs', fav: true, cat: 'haupt', title: 'Lachsfilet mit Kräuterbutter & Kartoffeln', icon: '🐟', min: 25, tags: ['fisch', 'schnell', 'ofen'], plate: { kh: 1, ew: 1, gm: 1 },
    ing: [['2', 'Lachsfilets (frisch oder TK, aufgetaut)'], ['1 Rolle', 'Kräuterbutter'], ['600 g', 'Kartoffeln (klein, festkochend)'], ['400 g', 'Brokkoli'], ['½', 'Zitrone']],
    steps: [['Kartoffeln in Salzwasser kochen (die kleinen mit Schale).', 20], ['Ofen auf 200 °C. Lachs in eine Form, salzen, je 2 Scheiben Kräuterbutter drauf.'], ['Lachs in den Ofen.', 15],
            ['Brokkoli in Röschen die letzten 7 Minuten zu den Kartoffeln ins Wasser.', 7], ['Anrichten, Zitrone drüber, restliche Kräuterbutter auf die Kartoffeln.']] },
  { id: 'gulasch', fav: true, cat: 'haupt', title: 'Gulasch aus einem Topf', icon: '🥘', min: 140, tags: ['deftig', 'österreichisch', 'schmoren'], plate: { kh: 1, ew: 1, gm: 1 },
    note: '20 Minuten Arbeit, dann köchelt er von allein. Am nächsten Tag noch besser.',
    ing: [['600 g', 'Rindergulasch (fertig gewürfelt)'], ['3', 'Zwiebeln'], ['1', 'rote Paprika'], ['2 EL', 'Paprikapulver edelsüß'], ['2 EL', 'Tomatenmark'], ['500 ml', 'Brühe'], ['250 g', 'Spirelli oder 1 Baguette']],
    steps: [['Zwiebeln und Paprika würfeln.'], ['Fleisch in einem großen Topf mit Öl kräftig anbraten (in 2 Portionen, dann wird’s braun statt grau).', 8], ['Zwiebeln dazu, 5 Minuten mitbraten, dann Paprikapulver und Tomatenmark kurz mitrösten.', 5],
            ['Brühe und Paprika dazu, Deckel drauf, ganz klein köcheln lassen.', 120], ['Zum Schluss Nudeln nach Packung kochen (oder Baguette aufbacken). Salzen, fertig.']] },
  { id: 'pilzrisotto', fav: true, cat: 'haupt', title: 'Pilzrisotto aus dem Ofen (ohne Rühren)', icon: '🍄', min: 35, tags: ['pilze', 'ofen', 'vegetarisch'], plate: { kh: 1, ew: 0, gm: 1 },
    ing: [['200 g', 'Risottoreis'], ['300 g', 'Champignons'], ['1', 'Zwiebel'], ['700 ml', 'Gemüsebrühe (heiß)'], ['50 g', 'Parmesan'], ['1 EL', 'Butter']],
    steps: [['Ofen auf 200 °C. Zwiebel würfeln, Pilze in Scheiben.'], ['In einem ofenfesten Topf Zwiebel in Butter glasig, Pilze 3 Minuten mitbraten, Reis kurz mitrühren.', 5],
            ['Heiße Brühe drauf, umrühren, Deckel drauf, ab in den Ofen.', 25], ['Raus, Parmesan rein, einmal kräftig umrühren – cremig. Pfeffer drüber.']] },
  { id: 'feldsalat', fav: true, cat: 'salat', title: 'Feldsalat mit Essig-Öl-Dressing', icon: '🥗', min: 10, tags: ['schnell', 'beilage'], plate: { kh: 0, ew: 0, gm: 1 },
    ing: [['150 g', 'Feldsalat'], ['3 EL', 'Öl (Sonnenblume oder Raps)'], ['2 EL', 'Essig (Weißwein oder Balsamico hell)'], ['1 TL', 'Senf'], ['1 TL', 'Zucker oder Honig']],
    steps: [['Feldsalat waschen und gut trocken schleudern (sonst hält das Dressing nicht).'], ['Essig, Senf, Zucker, Salz und Pfeffer verrühren, dann das Öl dazu.'], ['Erst kurz vorm Essen über den Salat – er fällt sonst zusammen.']] },
  { id: 'eis-himbeeren', fav: true, cat: 'dessert', title: 'Vanilleeis mit heißen Himbeeren', icon: '🍨', min: 8, tags: ['schnell', 'süß'],
    ing: [['4 Kugeln', 'Vanilleeis'], ['250 g', 'Himbeeren (TK)'], ['2 EL', 'Zucker'], ['1 Päckchen', 'Vanillezucker']],
    steps: [['Himbeeren mit Zucker und Vanillezucker in einem kleinen Topf erhitzen, bis sie sprudeln.', 5], ['Eis in Schalen, heiße Himbeeren drüber. Sofort essen!']] },
  { id: 'toast-hawaii', fav: true, cat: 'haupt', title: 'Toast Hawaii', icon: '🍍', min: 15, tags: ['schnell', 'ofen', 'retro'], plate: { kh: 1, ew: 1, gm: 0 },
    ing: [['4 Scheiben', 'Toastbrot'], ['4 Scheiben', 'Kochschinken'], ['4 Scheiben', 'Ananas (Dose)'], ['4 Scheiben', 'Käse (Gouda oder Scheiblettenkäse)'], ['etwas', 'Butter']],
    steps: [['Ofen auf 200 °C. Toast dünn buttern.'], ['Schinken, Ananas, Käse drauf (in die Ananas-Mitte eine Cocktailkirsche, wenn du’s retro magst).'], ['Ab in den Ofen, bis der Käse blubbert.', 10]] },
  { id: 'pizza-hawaii', fav: true, cat: 'haupt', title: 'Pizza Hawaii vom Blech', icon: '🍕', min: 25, tags: ['ofen', 'retro'], plate: { kh: 1, ew: 1, gm: 0 },
    ing: [['1 Rolle', 'Pizzateig (Kühlregal)'], ['200 ml', 'passierte Tomaten'], ['150 g', 'Kochschinken'], ['1 kleine Dose', 'Ananas'], ['200 g', 'geriebener Käse (Mozzarella oder Gouda)'], ['1 TL', 'Oregano']],
    steps: [['Ofen auf 220 °C. Teig mit dem Papier aufs Blech rollen.'], ['Tomaten mit Salz und Oregano verrühren, draufstreichen.'], ['Schinken, Ananas, Käse drauf.'], ['Backen, bis der Rand goldbraun ist.', 15]] },

  { id: 'ofenomelett', fav: true, cat: 'haupt', title: 'Omelett mit Tomaten & Käse aus dem Ofen', icon: '🍳', min: 25, tags: ['ofen', 'schnell', 'vegetarisch', 'eier'], plate: { kh: 0, ew: 1, gm: 1 },
    note: 'Kein Wenden, kein Zerreißen – der Ofen macht’s gleichmäßig.',
    ing: [['6', 'Eier'], ['100 ml', 'Milch'], ['250 g', 'Kirschtomaten'], ['100 g', 'geriebener Käse'], ['etwas', 'Schnittlauch oder Basilikum'], ['etwas', 'Butter für die Form']],
    steps: [['Ofen auf 180 °C. Eine Auflaufform (oder ofenfeste Pfanne) buttern.'], ['Eier mit Milch, Salz und Pfeffer verquirlen, in die Form.'], ['Tomaten halbieren und reinlegen, Käse drüberstreuen.'],
            ['Ab in den Ofen, bis es in der Mitte nicht mehr wackelt.', 20], ['Kräuter drüber, in Stücke schneiden.']] },

  // ---------- passt zu ihr (deftig, Hausmannskost, Österreich/Schweden, Ofen) ----------
  { id: 'bolognese', cat: 'haupt', title: 'Spaghetti Bolognese (schnelle Version)', icon: '🍝', min: 30, tags: ['nudeln', 'klassiker'], plate: { kh: 1, ew: 1, gm: 1 },
    ing: [['250 g', 'Spaghetti'], ['300 g', 'Rinderhack'], ['1', 'Zwiebel'], ['1', 'Karotte'], ['500 g', 'passierte Tomaten'], ['1 EL', 'Tomatenmark'], ['etwas', 'Parmesan']],
    steps: [['Zwiebel würfeln, Karotte fein reiben.'], ['Hack krümelig braten, Zwiebel und Karotte mitbraten.', 6], ['Tomatenmark kurz mitrösten, passierte Tomaten dazu, salzen, pfeffern, köcheln lassen.', 15],
            ['Währenddessen Spaghetti nach Packung kochen.', 10], ['Soße auf die Nudeln, Parmesan drüber.']] },
  { id: 'napoli', cat: 'haupt', title: 'Nudeln mit Tomatensoße', icon: '🍅', min: 15, tags: ['nudeln', 'schnell', 'vegetarisch'], plate: { kh: 1, ew: 0, gm: 1 },
    note: 'Lecker – aber allein fehlt das Eiweiß. Nimm unten was dazu!',
    ing: [['250 g', 'Nudeln'], ['500 g', 'passierte Tomaten'], ['1', 'Knoblauchzehe'], ['1 TL', 'Zucker'], ['etwas', 'Basilikum oder Oregano']],
    steps: [['Nudeln nach Packung kochen.', 10], ['Knoblauch fein in etwas Olivenöl anschwitzen, Tomaten dazu, Salz, Zucker, Kräuter – 8 Minuten köcheln.', 8], ['Mischen, fertig.']] },
  { id: 'kaesespaetzle', cat: 'haupt', title: 'Käsespätzle mit Röstzwiebeln', icon: '🧀', min: 20, tags: ['deftig', 'österreichisch', 'vegetarisch'], plate: { kh: 1, ew: 1, gm: 0 },
    ing: [['500 g', 'Spätzle (Kühlregal)'], ['200 g', 'Bergkäse oder Emmentaler (gerieben)'], ['1 Becher', 'Röstzwiebeln'], ['1 EL', 'Butter'], ['etwas', 'Schnittlauch']],
    steps: [['Spätzle in einer großen Pfanne mit Butter anbraten.', 5], ['Käse drüber, Deckel drauf, Hitze runter, bis er geschmolzen ist.', 3], ['Röstzwiebeln und Schnittlauch drüber, pfeffern.']] },
  { id: 'ofenhaehnchen', cat: 'haupt', title: 'Hähnchen mit Kartoffeln & Gemüse vom Blech', icon: '🍗', min: 45, tags: ['ofen', 'einfach'], plate: { kh: 1, ew: 1, gm: 1 },
    ing: [['4', 'Hähnchenschenkel (oder 2 Brüste)'], ['600 g', 'Kartoffeln (Drillinge)'], ['2', 'Paprika'], ['1', 'Zucchini'], ['1', 'rote Zwiebel'], ['3 EL', 'Olivenöl'], ['2 TL', 'Paprikapulver']],
    steps: [['Ofen auf 200 °C. Kartoffeln halbieren, Gemüse in grobe Stücke.'], ['Alles aufs Blech, mit Öl, Salz und Paprikapulver vermischen.'], ['Hähnchen obendrauf, auch würzen.'], ['Ab in den Ofen – fertig, wenn die Haut knusprig ist.', 40]] },
  { id: 'rahmpilze', cat: 'haupt', title: 'Rahmschwammerl mit Semmelknödel', icon: '🍄', min: 25, tags: ['pilze', 'österreichisch', 'vegetarisch'], plate: { kh: 1, ew: 0, gm: 1 },
    ing: [['400 g', 'Champignons'], ['1', 'Zwiebel'], ['200 ml', 'Sahne'], ['1 Packung', 'Semmelknödel im Kochbeutel'], ['etwas', 'Petersilie']],
    steps: [['Knödel nach Packung kochen.', 20], ['Pilze in Scheiben, Zwiebel würfeln, zusammen in Butter braten, bis die Pilze braun sind.', 8], ['Sahne dazu, salzen, pfeffern, 3 Minuten köcheln, Petersilie drüber.', 3]] },
  { id: 'fischstaebchen', cat: 'haupt', title: 'Fischstäbchen mit Püree & Rahmspinat', icon: '🐠', min: 20, tags: ['fisch', 'schnell', 'kindheit'], plate: { kh: 1, ew: 1, gm: 1 },
    ing: [['15 Stück', 'Fischstäbchen (TK)'], ['1 Beutel', 'Kartoffelpüree (Pulver)'], ['400 ml', 'Milch'], ['450 g', 'Rahmspinat (TK)']],
    steps: [['Fischstäbchen im Ofen oder in der Pfanne nach Packung.', 15], ['Rahmspinat im Topf auftauen und erhitzen.', 10], ['Püree anrühren. Fertig – Kindheit auf dem Teller.']] },
  { id: 'kartoffelsuppe', cat: 'haupt', title: 'Kartoffelsuppe mit Würstchen', icon: '🥣', min: 35, tags: ['deftig', 'suppe', 'hausmannskost'], plate: { kh: 1, ew: 1, gm: 1 },
    ing: [['800 g', 'Kartoffeln (mehligkochend)'], ['1 Bund', 'Suppengrün (TK geht auch)'], ['1 l', 'Gemüsebrühe'], ['4', 'Wiener Würstchen'], ['100 ml', 'Sahne'], ['1 Prise', 'Majoran']],
    steps: [['Kartoffeln schälen und würfeln, Suppengrün klein schneiden.'], ['Alles mit der Brühe in einen Topf, weich kochen.', 20], ['Grob stampfen (ein paar Stücke dürfen bleiben), Sahne und Majoran dazu.'],
            ['Würstchen in Scheiben rein, 5 Minuten ziehen lassen.', 5]] },
  { id: 'geschnetzeltes', cat: 'haupt', title: 'Hähnchen-Geschnetzeltes mit Reis', icon: '🍚', min: 25, tags: ['schnell', 'cremig'], plate: { kh: 1, ew: 1, gm: 1 },
    ing: [['2', 'Hähnchenbrüste'], ['250 g', 'Champignons'], ['1', 'Zwiebel'], ['200 ml', 'Sahne'], ['2 Beutel', 'Reis im Kochbeutel'], ['150 g', 'Erbsen (TK)']],
    steps: [['Reis nach Packung kochen.', 15], ['Hähnchen in Streifen, in einer Pfanne goldbraun braten, rausnehmen.', 6], ['Zwiebel und Pilze in derselben Pfanne braten.', 5],
            ['Sahne und Erbsen dazu, Hähnchen zurück, salzen, pfeffern, 3 Minuten köcheln.', 3]] },
  { id: 'chili', cat: 'haupt', title: 'Chili con Carne', icon: '🌶️', min: 35, tags: ['deftig', 'eintopf'], plate: { kh: 1, ew: 1, gm: 1 },
    ing: [['400 g', 'Rinderhack'], ['1', 'Zwiebel'], ['1 Dose', 'Kidneybohnen'], ['1 Dose', 'Mais'], ['1 Dose', 'gehackte Tomaten'], ['1 TL', 'Kreuzkümmel'], ['1 TL', 'Chili (mild bis scharf)'], ['1', 'Baguette']],
    steps: [['Zwiebel würfeln, Hack krümelig braten, Zwiebel mitbraten.', 6], ['Gewürze kurz mitrösten, Tomaten, abgetropfte Bohnen und Mais dazu.'], ['Köcheln lassen, salzen.', 20], ['Mit Baguette (oder Reis) essen. Ein Klecks Schmand obendrauf ist erlaubt.']] },
  { id: 'schnitzel', cat: 'haupt', title: 'Schnitzel mit Kartoffelsalat', icon: '🥩', min: 20, tags: ['österreichisch', 'klassiker'], plate: { kh: 1, ew: 1, gm: 0 },
    note: 'Abkürzung: fertig panierte Schnitzel vom Metzger und Kartoffelsalat aus dem Kühlregal.',
    ing: [['2', 'Schnitzel (fertig paniert)'], ['500 g', 'Kartoffelsalat (Kühlregal)'], ['½', 'Zitrone'], ['reichlich', 'Öl zum Braten']],
    steps: [['Reichlich Öl in einer Pfanne heiß werden lassen.'], ['Schnitzel pro Seite ca. 3 Minuten goldbraun braten.', 6], ['Auf Küchenpapier abtropfen lassen, mit Zitrone und Kartoffelsalat servieren.']] },
  { id: 'ofenkartoffel', cat: 'haupt', title: 'Ofenkartoffel mit Kräuterquark & Lachs', icon: '🥔', min: 50, tags: ['ofen', 'einfach'], plate: { kh: 1, ew: 1, gm: 0 },
    ing: [['2 große', 'Kartoffeln (mehligkochend)'], ['250 g', 'Kräuterquark'], ['100 g', 'Räucherlachs'], ['etwas', 'Schnittlauch']],
    steps: [['Ofen auf 200 °C. Kartoffeln waschen, mehrmals mit der Gabel einstechen, in Alufolie wickeln.'], ['Ab in den Ofen, bis sie ganz weich sind.', 50], ['Aufschneiden, Quark rein, Lachs drauf, Schnittlauch drüber.']] },

  // ---------- Salate ----------
  { id: 'gurkensalat', cat: 'salat', title: 'Gurkensalat mit Dill', icon: '🥒', min: 10, tags: ['schnell', 'beilage'], plate: { kh: 0, ew: 0, gm: 1 },
    ing: [['1', 'Salatgurke'], ['100 g', 'Joghurt oder saure Sahne'], ['1 EL', 'Essig'], ['1 TL', 'Zucker'], ['etwas', 'Dill (TK)']],
    steps: [['Gurke in dünne Scheiben hobeln.'], ['Joghurt, Essig, Zucker, Salz, Pfeffer, Dill verrühren, untermischen.']] },
  { id: 'tomatensalat', cat: 'salat', title: 'Tomatensalat mit Zwiebeln', icon: '🍅', min: 10, tags: ['schnell', 'beilage'], plate: { kh: 0, ew: 0, gm: 1 },
    ing: [['4', 'Tomaten'], ['½', 'rote Zwiebel'], ['2 EL', 'Olivenöl'], ['1 EL', 'Balsamico'], ['etwas', 'Basilikum']],
    steps: [['Tomaten in Scheiben, Zwiebel in feine Ringe.'], ['Salz, Pfeffer, Essig und Öl drüber, 5 Minuten ziehen lassen.']] },
  { id: 'krautsalat', cat: 'salat', title: 'Krautsalat (wie beim Wirt)', icon: '🥬', min: 15, tags: ['beilage', 'österreichisch'], plate: { kh: 0, ew: 0, gm: 1 },
    ing: [['400 g', 'Weißkohl'], ['3 EL', 'Essig'], ['3 EL', 'Öl'], ['1 TL', 'Zucker'], ['½ TL', 'Kümmel']],
    steps: [['Kohl ganz fein hobeln, mit 1 TL Salz kräftig durchkneten, bis er weich wird.'], ['Essig, Öl, Zucker, Kümmel dazu, mindestens 10 Minuten ziehen lassen.', 10]] },
  { id: 'caprese', cat: 'salat', title: 'Tomate-Mozzarella', icon: '🧀', min: 5, tags: ['schnell'], plate: { kh: 0, ew: 1, gm: 1 },
    ing: [['3', 'Tomaten'], ['1 Kugel', 'Mozzarella'], ['2 EL', 'Olivenöl'], ['etwas', 'Basilikum'], ['1 EL', 'Balsamico-Creme']],
    steps: [['Tomaten und Mozzarella in Scheiben, abwechselnd hinlegen.'], ['Salz, Pfeffer, Öl, Basilikum, Balsamico-Creme drüber.']] },

  // ---------- Desserts ----------
  { id: 'kaiserschmarrn', cat: 'dessert', title: 'Kaiserschmarrn', icon: '🥞', min: 20, tags: ['österreichisch', 'süß'],
    ing: [['3', 'Eier'], ['150 g', 'Mehl'], ['250 ml', 'Milch'], ['2 EL', 'Zucker'], ['1 EL', 'Butter'], ['etwas', 'Puderzucker'], ['1 Glas', 'Apfelmus']],
    steps: [['Eier, Mehl, Milch, Zucker, Prise Salz glatt rühren.'], ['Butter in einer Pfanne, Teig rein, bei mittlerer Hitze stocken lassen.', 5], ['Wenden (in Vierteln geht’s leichter), dann mit zwei Gabeln in Stücke reißen.', 3], ['Puderzucker drüber, Apfelmus dazu.']] },
  { id: 'milchreis', cat: 'dessert', title: 'Milchreis mit Zimt & Kirschen', icon: '🍒', min: 35, tags: ['süß', 'gemütlich'],
    ing: [['125 g', 'Milchreis'], ['500 ml', 'Milch'], ['2 EL', 'Zucker'], ['1 Glas', 'Sauerkirschen'], ['etwas', 'Zimt & Zucker']],
    steps: [['Milch mit Zucker aufkochen, Reis rein.'], ['Ganz klein köcheln lassen, ab und zu umrühren (sonst brennt er an).', 30], ['Mit Zimt-Zucker und Kirschen essen – warm oder kalt.']] },
  { id: 'tiramisu-glas', cat: 'dessert', title: 'Tiramisu im Glas (ohne Ei)', icon: '☕', min: 15, tags: ['süß', 'ohne kochen'],
    ing: [['250 g', 'Mascarpone'], ['250 g', 'Magerquark'], ['2 EL', 'Zucker'], ['8', 'Löffelbiskuits'], ['1 Tasse', 'kalter Kaffee'], ['etwas', 'Kakaopulver']],
    steps: [['Mascarpone, Quark und Zucker glatt rühren.'], ['Löffelbiskuits kurz in den Kaffee tunken, in Gläser bröseln.'], ['Creme drauf, noch eine Schicht, Kakao drüber. 1 Stunde kalt stellen, wenn du’s aushältst.', 60]] },
  { id: 'bratapfel', cat: 'dessert', title: 'Bratapfel aus der Mikrowelle', icon: '🍎', min: 10, tags: ['süß', 'herbst', 'schnell'],
    ing: [['2', 'Äpfel'], ['2 EL', 'Rosinen oder Nüsse'], ['1 EL', 'Honig'], ['etwas', 'Zimt'], ['2 Kugeln', 'Vanilleeis (wer mag)']],
    steps: [['Kerngehäuse ausstechen (Apfelausstecher oder Löffel).'], ['Rosinen, Honig, Zimt reinfüllen.'], ['In einer Schale in die Mikrowelle (600 Watt), bis sie weich sind.', 5], ['Mit Vanilleeis.']] },
  { id: 'schokoerdbeeren', cat: 'dessert', title: 'Erdbeeren in Schokolade', icon: '🍓', min: 15, tags: ['süß', 'ohne kochen'],
    ing: [['250 g', 'Erdbeeren'], ['100 g', 'Zartbitter- oder Vollmilchschokolade']],
    steps: [['Schokolade in einer Schale in der Mikrowelle schmelzen (immer 30 Sekunden, dann umrühren).'], ['Erdbeeren reintunken, auf Backpapier legen, 10 Minuten kühlen.', 10]] },

  // ---------- Drinks ohne Alkohol ----------
  { id: 'virgin-colada', cat: 'drink', title: 'Virgin Piña Colada', icon: '🍍', min: 5, tags: ['hawaii', 'süß'],
    ing: [['200 ml', 'Ananassaft'], ['80 ml', 'Kokosmilch (oder Kokossirup)'], ['1 Handvoll', 'Eiswürfel'], ['1 Stück', 'Ananas zur Deko']],
    steps: [['Alles mit dem Eis in den Mixer (oder kräftig im Shaker/Glas mit Deckel schütteln).'], ['In ein großes Glas, Ananas an den Rand. Urlaub.']] },
  { id: 'virgin-mojito', cat: 'drink', title: 'Virgin Mojito', icon: '🌿', min: 5, tags: ['frisch'],
    ing: [['1', 'Limette'], ['1 Handvoll', 'Minze'], ['2 TL', 'brauner Zucker'], ['200 ml', 'Sprudelwasser oder Ginger Ale'], ['viel', 'Crushed Ice']],
    steps: [['Limette achteln, mit Zucker und Minze im Glas mit einem Löffel zerdrücken.'], ['Glas mit Eis füllen, mit Sprudel aufgießen, umrühren.']] },
  { id: 'hugo', cat: 'drink', title: 'Hugo ohne Alkohol', icon: '🥂', min: 3, tags: ['frisch', 'gemütlich'],
    ing: [['2 cl', 'Holunderblütensirup'], ['200 ml', 'alkoholfreier Sekt oder Sprudel'], ['ein paar', 'Minzblätter'], ['1 Scheibe', 'Limette'], ['einige', 'Eiswürfel']],
    steps: [['Sirup, Eis, Minze, Limette ins Weinglas.'], ['Mit Sekt aufgießen, einmal umrühren.']] },
  { id: 'himbeerlimo', cat: 'drink', title: 'Himbeer-Limonade', icon: '🍹', min: 10, tags: ['frisch', 'süß'],
    ing: [['150 g', 'Himbeeren (TK)'], ['2 EL', 'Zucker'], ['1', 'Zitrone'], ['500 ml', 'Sprudelwasser']],
    steps: [['Himbeeren mit Zucker zerdrücken (oder kurz pürieren), Zitronensaft dazu.'], ['Durch ein Sieb in einen Krug, mit Sprudel und Eis auffüllen.']] },
  { id: 'apfel-ingwer', cat: 'drink', title: 'Apfel-Ingwer-Spritz', icon: '🍏', min: 5, tags: ['frisch', 'herbst'],
    ing: [['150 ml', 'naturtrüber Apfelsaft'], ['1 Stück (daumengroß)', 'Ingwer'], ['150 ml', 'Sprudelwasser'], ['1 Zweig', 'Rosmarin (wer mag)']],
    steps: [['Ingwer in dünne Scheiben, mit dem Saft ins Glas.'], ['Eis und Sprudel drauf, Rosmarin rein.']] },
  { id: 'kakao', cat: 'drink', title: 'Heiße Schokolade deluxe', icon: '☕', min: 7, tags: ['gemütlich', 'süß', 'herbst'],
    ing: [['400 ml', 'Milch'], ['60 g', 'Schokolade (Vollmilch oder Zartbitter)'], ['1 Prise', 'Zimt'], ['etwas', 'Sprühsahne oder Marshmallows']],
    steps: [['Milch erhitzen (nicht kochen), Schokolade in Stücken reinrühren, bis sie geschmolzen ist.', 5], ['In die große Tasse, Sahne oder Marshmallows obendrauf.']] },
];

// What a plate can be topped up with when something's missing (kh / ew / gm). One tap = it's part of the meal.
export const SIDES = [
  { id: 's-erbsen', g: 'gm', title: 'Erbsen mit Butter', ing: [['300 g', 'Erbsen (TK)']], step: ['Erbsen mit etwas Wasser und Butter im Topf warm machen.', 5] },
  { id: 's-brokkoli', g: 'gm', title: 'Brokkoli', ing: [['400 g', 'Brokkoli']], step: ['Brokkoli in Röschen, in Salzwasser bissfest kochen.', 7] },
  { id: 's-feldsalat', g: 'gm', title: 'Feldsalat', ing: [['150 g', 'Feldsalat'], ['', 'Essig, Öl, Senf']], step: ['Feldsalat waschen, Essig-Öl-Dressing drüber (siehe Rezept).'] },
  { id: 's-gurke', g: 'gm', title: 'Gurkensalat', ing: [['1', 'Salatgurke'], ['100 g', 'Joghurt']], step: ['Gurke hobeln, mit Joghurt, Essig, Salz, Dill mischen.'] },
  { id: 's-rohkost', g: 'gm', title: 'Rohkost-Sticks', ing: [['2', 'Karotten'], ['1', 'Paprika'], ['½', 'Gurke']], step: ['Gemüse in Sticks schneiden – fertig.'] },
  { id: 's-spinat', g: 'gm', title: 'Rahmspinat', ing: [['450 g', 'Rahmspinat (TK)']], step: ['Rahmspinat im Topf erhitzen.', 10] },
  { id: 's-haehnchen', g: 'ew', title: 'Hähnchenstreifen', ing: [['250 g', 'Hähnchenbrust']], step: ['Hähnchen in Streifen, in der Pfanne goldbraun braten, salzen.', 8] },
  { id: 's-thunfisch', g: 'ew', title: 'Thunfisch', ing: [['1 Dose', 'Thunfisch']], step: ['Thunfisch abtropfen lassen und unterheben.'] },
  { id: 's-mozzarella', g: 'ew', title: 'Mozzarella', ing: [['1 Kugel', 'Mozzarella']], step: ['Mozzarella zupfen und drüber.'] },
  { id: 's-ei', g: 'ew', title: 'Spiegelei', ing: [['2', 'Eier']], step: ['Eier in der Pfanne braten, bis das Weiße fest ist.', 4] },
  { id: 's-garnelen', g: 'ew', title: 'Garnelen', ing: [['200 g', 'Garnelen (TK, aufgetaut)']], step: ['Garnelen mit etwas Knoblauch in der Pfanne braten, bis sie rosa sind.', 4] },
  { id: 's-schinken', g: 'ew', title: 'Schinkenwürfel', ing: [['125 g', 'Schinkenwürfel']], step: ['Schinkenwürfel knusprig anbraten.', 4] },
  { id: 's-bohnen', g: 'ew', title: 'Kidneybohnen', ing: [['1 Dose', 'Kidneybohnen']], step: ['Bohnen abspülen und unterheben.'] },
  { id: 's-brot', g: 'kh', title: 'Baguette', ing: [['1', 'Baguette (zum Aufbacken)']], step: ['Baguette nach Packung aufbacken.', 8] },
  { id: 's-reis', g: 'kh', title: 'Reis', ing: [['2 Beutel', 'Reis im Kochbeutel']], step: ['Reis nach Packung kochen.', 15] },
  { id: 's-kartoffeln', g: 'kh', title: 'Salzkartoffeln', ing: [['600 g', 'Kartoffeln']], step: ['Kartoffeln schälen, in Salzwasser kochen.', 20] },
];
// Which sides fit which dish best (first ones are suggested first)
export const SIDE_HINTS = { napoli: ['s-haehnchen', 's-thunfisch', 's-mozzarella', 's-garnelen'], pilzrisotto: ['s-haehnchen', 's-garnelen', 's-ei'], rahmpilze: ['s-ei', 's-schinken'],
  'toast-hawaii': ['s-feldsalat', 's-rohkost', 's-gurke'], 'pizza-hawaii': ['s-feldsalat', 's-rohkost', 's-gurke'], kaesespaetzle: ['s-feldsalat', 's-gurke'],
  schnitzel: ['s-gurke', 's-feldsalat'], ofenkartoffel: ['s-feldsalat', 's-gurke', 's-rohkost'], ofenomelett: ['s-brot', 's-kartoffeln'] };
// After cooking: how was it?
export const TASTE = [['😍', 'Lieblingsessen', 3], ['🙂', 'Gut', 2], ['😕', 'Nicht nochmal', 1]];
